#pragma once
#include <QMainWindow>
#include "ui_MainWindow.h" // generated by QtDesigner
#include "ui/UIUpdater.hpp"

class MainWindow : public QMainWindow, private Ui::MainWindow
{
    Q_OBJECT
public:
    explicit MainWindow(UIUpdater *updater, QWidget *parent = nullptr);

private slots:
    void handleMetrics(double slippage,
                       double fees,
                       double impact,
                       double netCost);
};